version: '3.8'

services:
  backend:
    build: ./HelloEvents-BackEnd
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./HelloEvents-FrontEnd
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge